"""empty message

Revision ID: b9fffbf38c5e
Revises: 
Create Date: 2018-06-21 11:49:59.203584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fffbf38c5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cate',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('cname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_index(op.f('ix_cate_cname'), 'cate', ['cname'], unique=True)
    op.create_table('shop',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('sub_title', sa.String(length=512), nullable=True),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('promote_price', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('cate_id', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cate_id'], ['cate.cid'], ),
    sa.PrimaryKeyConstraint('shop_id')
    )
    op.create_index(op.f('ix_shop_name'), 'shop', ['name'], unique=False)
    op.create_index(op.f('ix_shop_sub_title'), 'shop', ['sub_title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_sub_title'), table_name='shop')
    op.drop_index(op.f('ix_shop_name'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_cate_cname'), table_name='cate')
    op.drop_table('cate')
    # ### end Alembic commands ###
