"""empty message

Revision ID: be9c4cc692a7
Revises: 96c6f47721db
Create Date: 2018-06-22 12:41:25.087866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9c4cc692a7'
down_revision = '96c6f47721db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('per_id', sa.Integer(), nullable=False),
    sa.Column('per_name', sa.String(length=64), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('per_id')
    )
    op.create_index(op.f('ix_permission_per_name'), 'permission', ['per_name'], unique=True)
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_role_role_name'), 'role', ['role_name'], unique=True)
    op.create_table('role_permission_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('per_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['per_id'], ['permission.per_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permission_relation')
    op.drop_index(op.f('ix_role_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_per_name'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
